# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('Direccion', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Celular', models.CharField(max_length=200)),
                ('web', models.CharField(max_length=200)),
            ],
        ),
    ]
